name: pr
run-name: >-
  ${{github.event.pull_request.title}}
  (#${{github.event.number}})

on:
  pull_request:
    branches:
      - develop
      - backports/**
    paths-ignore:
      - '**.rst'
      - '**.md'
      - 'scripts/dev'

concurrency:
  group: pr-${{github.ref}}-${{github.event.number}}-${{github.workflow}}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build-full.yml

  # Specifying a dependent job allows us to select a single "requires" check
  all:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Success
      run: "true"

# vim: set nowrap tw=100:
