name: pr
run-name: >-
  ${{github.event.pull_request.title}}
  (#${{github.event.number}})

on:
  pull_request:
    branches:
      - develop
      - backports/**
    paths-ignore:
      - '**.rst'
      - '**.md'
      - 'scripts/dev'

concurrency:
  group: pr-${{github.ref}}-${{github.event.number}}-${{github.workflow}}
  cancel-in-progress: true

jobs:
  build-fast:
    uses: ./.github/workflows/build-fast.yml
  doc:
    uses: ./.github/workflows/doc.yml
  all-prechecks:
    needs: [build-fast, doc]
    runs-on: ubuntu-latest
    steps:
    - name: Success
      run: "true"
  build:
    needs: [all-prechecks]
    uses: ./.github/workflows/build-full.yml

  # Specifying a dependent job allows us to select a single "requires" check in the project GitHub settings
  all:
    if: ${{ always() }}
    needs:
    - build
    runs-on: ubuntu-latest
    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}

# vim: set nowrap tw=100:
