name: push
# TODO: improve run name using commit title (`message` includes details as well)
# run-name: >-
#   ${{github.ref_name}}:
#   ${{github.event.head_commit.message}}
#   (${{github.event.pusher.name}})

on:
  push:
    branches:
      - develop
      - backports/**

concurrency:
  group: push-${{github.ref}}-${{github.run_number}}-${{github.workflow}}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build-full.yml
  # TODO: build and push documentation

# vim: set nowrap tw=100:
